// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Mmap2Stream_Mmap2Stream,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.430900,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=624,HLS_SYN_LUT=834,HLS_VERSION=2020_2}" *)

module Mmap2Stream (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mmap_AWVALID,
        m_axi_mmap_AWREADY,
        m_axi_mmap_AWADDR,
        m_axi_mmap_AWID,
        m_axi_mmap_AWLEN,
        m_axi_mmap_AWSIZE,
        m_axi_mmap_AWBURST,
        m_axi_mmap_AWLOCK,
        m_axi_mmap_AWCACHE,
        m_axi_mmap_AWPROT,
        m_axi_mmap_AWQOS,
        m_axi_mmap_AWREGION,
        m_axi_mmap_AWUSER,
        m_axi_mmap_WVALID,
        m_axi_mmap_WREADY,
        m_axi_mmap_WDATA,
        m_axi_mmap_WSTRB,
        m_axi_mmap_WLAST,
        m_axi_mmap_WID,
        m_axi_mmap_WUSER,
        m_axi_mmap_ARVALID,
        m_axi_mmap_ARREADY,
        m_axi_mmap_ARADDR,
        m_axi_mmap_ARID,
        m_axi_mmap_ARLEN,
        m_axi_mmap_ARSIZE,
        m_axi_mmap_ARBURST,
        m_axi_mmap_ARLOCK,
        m_axi_mmap_ARCACHE,
        m_axi_mmap_ARPROT,
        m_axi_mmap_ARQOS,
        m_axi_mmap_ARREGION,
        m_axi_mmap_ARUSER,
        m_axi_mmap_RVALID,
        m_axi_mmap_RREADY,
        m_axi_mmap_RDATA,
        m_axi_mmap_RLAST,
        m_axi_mmap_RID,
        m_axi_mmap_RUSER,
        m_axi_mmap_RRESP,
        m_axi_mmap_BVALID,
        m_axi_mmap_BREADY,
        m_axi_mmap_BRESP,
        m_axi_mmap_BID,
        m_axi_mmap_BUSER,
        mmap_offset,
        n,
        stream_V_din,
        stream_V_full_n,
        stream_V_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_pp0_stage0 = 10'd256;
parameter    ap_ST_fsm_state12 = 10'd512;
parameter    C_M_AXI_MMAP_ID_WIDTH = 1;
parameter    C_M_AXI_MMAP_ADDR_WIDTH = 64;
parameter    C_M_AXI_MMAP_DATA_WIDTH = 32;
parameter    C_M_AXI_MMAP_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_WUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_RUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_BUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_USER_VALUE = 0;
parameter    C_M_AXI_MMAP_PROT_VALUE = 0;
parameter    C_M_AXI_MMAP_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_MMAP_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mmap_AWVALID;
input   m_axi_mmap_AWREADY;
output  [C_M_AXI_MMAP_ADDR_WIDTH - 1:0] m_axi_mmap_AWADDR;
output  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_AWID;
output  [7:0] m_axi_mmap_AWLEN;
output  [2:0] m_axi_mmap_AWSIZE;
output  [1:0] m_axi_mmap_AWBURST;
output  [1:0] m_axi_mmap_AWLOCK;
output  [3:0] m_axi_mmap_AWCACHE;
output  [2:0] m_axi_mmap_AWPROT;
output  [3:0] m_axi_mmap_AWQOS;
output  [3:0] m_axi_mmap_AWREGION;
output  [C_M_AXI_MMAP_AWUSER_WIDTH - 1:0] m_axi_mmap_AWUSER;
output   m_axi_mmap_WVALID;
input   m_axi_mmap_WREADY;
output  [C_M_AXI_MMAP_DATA_WIDTH - 1:0] m_axi_mmap_WDATA;
output  [C_M_AXI_MMAP_WSTRB_WIDTH - 1:0] m_axi_mmap_WSTRB;
output   m_axi_mmap_WLAST;
output  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_WID;
output  [C_M_AXI_MMAP_WUSER_WIDTH - 1:0] m_axi_mmap_WUSER;
output   m_axi_mmap_ARVALID;
input   m_axi_mmap_ARREADY;
output  [C_M_AXI_MMAP_ADDR_WIDTH - 1:0] m_axi_mmap_ARADDR;
output  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_ARID;
output  [7:0] m_axi_mmap_ARLEN;
output  [2:0] m_axi_mmap_ARSIZE;
output  [1:0] m_axi_mmap_ARBURST;
output  [1:0] m_axi_mmap_ARLOCK;
output  [3:0] m_axi_mmap_ARCACHE;
output  [2:0] m_axi_mmap_ARPROT;
output  [3:0] m_axi_mmap_ARQOS;
output  [3:0] m_axi_mmap_ARREGION;
output  [C_M_AXI_MMAP_ARUSER_WIDTH - 1:0] m_axi_mmap_ARUSER;
input   m_axi_mmap_RVALID;
output   m_axi_mmap_RREADY;
input  [C_M_AXI_MMAP_DATA_WIDTH - 1:0] m_axi_mmap_RDATA;
input   m_axi_mmap_RLAST;
input  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_RID;
input  [C_M_AXI_MMAP_RUSER_WIDTH - 1:0] m_axi_mmap_RUSER;
input  [1:0] m_axi_mmap_RRESP;
input   m_axi_mmap_BVALID;
output   m_axi_mmap_BREADY;
input  [1:0] m_axi_mmap_BRESP;
input  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_BID;
input  [C_M_AXI_MMAP_BUSER_WIDTH - 1:0] m_axi_mmap_BUSER;
input  [63:0] mmap_offset;
input  [63:0] n;
output  [32:0] stream_V_din;
input   stream_V_full_n;
output   stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_V_write;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    mmap_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [0:0] icmp_ln17_reg_167;
reg    mmap_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln17_1_reg_187;
reg    stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln17_1_reg_187_pp0_iter1_reg;
wire    mmap_AWREADY;
wire    mmap_WREADY;
reg    mmap_ARVALID;
wire    mmap_ARREADY;
wire   [31:0] mmap_ARLEN;
wire    mmap_RVALID;
reg    mmap_RREADY;
wire   [31:0] mmap_RDATA;
wire    mmap_RLAST;
wire   [0:0] mmap_RID;
wire   [0:0] mmap_RUSER;
wire   [1:0] mmap_RRESP;
wire    mmap_BVALID;
wire   [1:0] mmap_BRESP;
wire   [0:0] mmap_BID;
wire   [0:0] mmap_BUSER;
reg   [63:0] i_reg_104;
wire   [0:0] icmp_ln17_fu_115_p2;
wire   [63:0] i_1_fu_146_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state9_pp0_stage0_iter0;
reg    ap_block_state10_pp0_stage0_iter1;
reg    ap_block_state11_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln17_1_fu_152_p2;
reg   [31:0] mmap_addr_read_reg_191;
wire    ap_CS_fsm_state8;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state9;
wire   [63:0] sext_ln17_fu_131_p1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_01001;
wire   [61:0] trunc_ln17_1_fu_121_p4;
wire    ap_CS_fsm_state12;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

Mmap2Stream_mmap_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MMAP_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MMAP_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MMAP_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MMAP_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MMAP_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MMAP_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MMAP_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MMAP_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MMAP_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MMAP_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MMAP_CACHE_VALUE ))
mmap_m_axi_U(
    .AWVALID(m_axi_mmap_AWVALID),
    .AWREADY(m_axi_mmap_AWREADY),
    .AWADDR(m_axi_mmap_AWADDR),
    .AWID(m_axi_mmap_AWID),
    .AWLEN(m_axi_mmap_AWLEN),
    .AWSIZE(m_axi_mmap_AWSIZE),
    .AWBURST(m_axi_mmap_AWBURST),
    .AWLOCK(m_axi_mmap_AWLOCK),
    .AWCACHE(m_axi_mmap_AWCACHE),
    .AWPROT(m_axi_mmap_AWPROT),
    .AWQOS(m_axi_mmap_AWQOS),
    .AWREGION(m_axi_mmap_AWREGION),
    .AWUSER(m_axi_mmap_AWUSER),
    .WVALID(m_axi_mmap_WVALID),
    .WREADY(m_axi_mmap_WREADY),
    .WDATA(m_axi_mmap_WDATA),
    .WSTRB(m_axi_mmap_WSTRB),
    .WLAST(m_axi_mmap_WLAST),
    .WID(m_axi_mmap_WID),
    .WUSER(m_axi_mmap_WUSER),
    .ARVALID(m_axi_mmap_ARVALID),
    .ARREADY(m_axi_mmap_ARREADY),
    .ARADDR(m_axi_mmap_ARADDR),
    .ARID(m_axi_mmap_ARID),
    .ARLEN(m_axi_mmap_ARLEN),
    .ARSIZE(m_axi_mmap_ARSIZE),
    .ARBURST(m_axi_mmap_ARBURST),
    .ARLOCK(m_axi_mmap_ARLOCK),
    .ARCACHE(m_axi_mmap_ARCACHE),
    .ARPROT(m_axi_mmap_ARPROT),
    .ARQOS(m_axi_mmap_ARQOS),
    .ARREGION(m_axi_mmap_ARREGION),
    .ARUSER(m_axi_mmap_ARUSER),
    .RVALID(m_axi_mmap_RVALID),
    .RREADY(m_axi_mmap_RREADY),
    .RDATA(m_axi_mmap_RDATA),
    .RLAST(m_axi_mmap_RLAST),
    .RID(m_axi_mmap_RID),
    .RUSER(m_axi_mmap_RUSER),
    .RRESP(m_axi_mmap_RRESP),
    .BVALID(m_axi_mmap_BVALID),
    .BREADY(m_axi_mmap_BREADY),
    .BRESP(m_axi_mmap_BRESP),
    .BID(m_axi_mmap_BID),
    .BUSER(m_axi_mmap_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(mmap_ARVALID),
    .I_ARREADY(mmap_ARREADY),
    .I_ARADDR(sext_ln17_fu_131_p1),
    .I_ARID(1'd0),
    .I_ARLEN(mmap_ARLEN),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(mmap_RVALID),
    .I_RREADY(mmap_RREADY),
    .I_RDATA(mmap_RDATA),
    .I_RID(mmap_RID),
    .I_RUSER(mmap_RUSER),
    .I_RRESP(mmap_RRESP),
    .I_RLAST(mmap_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(mmap_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(mmap_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(mmap_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(mmap_BRESP),
    .I_BID(mmap_BID),
    .I_BUSER(mmap_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state9) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state9)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state9);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_1_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_reg_104 <= i_1_fu_146_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_reg_104 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln17_1_reg_187 <= icmp_ln17_1_fu_152_p2;
        icmp_ln17_1_reg_187_pp0_iter1_reg <= icmp_ln17_1_reg_187;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln17_reg_167 <= icmp_ln17_fu_115_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_1_reg_187 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mmap_addr_read_reg_191 <= mmap_RDATA;
    end
end

always @ (*) begin
    if ((icmp_ln17_1_fu_152_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state9 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state9 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln17_reg_167 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
        mmap_ARVALID = 1'b1;
    end else begin
        mmap_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_1_reg_187 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        mmap_RREADY = 1'b1;
    end else begin
        mmap_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln17_reg_167 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mmap_blk_n_AR = m_axi_mmap_ARREADY;
    end else begin
        mmap_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_1_reg_187 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        mmap_blk_n_R = m_axi_mmap_RVALID;
    end else begin
        mmap_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln17_1_reg_187_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        stream_V_blk_n = stream_V_full_n;
    end else begin
        stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln17_1_reg_187_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        stream_V_write = 1'b1;
    end else begin
        stream_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln17_reg_167 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((icmp_ln17_reg_167 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_io))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln17_1_fu_152_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln17_1_fu_152_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((stream_V_full_n == 1'b0) & (icmp_ln17_1_reg_187_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((mmap_RVALID == 1'b0) & (icmp_ln17_1_reg_187 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((stream_V_full_n == 1'b0) & (icmp_ln17_1_reg_187_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((mmap_RVALID == 1'b0) & (icmp_ln17_1_reg_187 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((stream_V_full_n == 1'b0) & (icmp_ln17_1_reg_187_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((mmap_RVALID == 1'b0) & (icmp_ln17_1_reg_187 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter1 = ((mmap_RVALID == 1'b0) & (icmp_ln17_1_reg_187 == 1'd0));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter2 = ((stream_V_full_n == 1'b0) & (icmp_ln17_1_reg_187_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln17_reg_167 == 1'd0) & (mmap_ARREADY == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_1_fu_146_p2 = (i_reg_104 + 64'd1);

assign icmp_ln17_1_fu_152_p2 = ((i_reg_104 == n) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_115_p2 = ((n == 64'd0) ? 1'b1 : 1'b0);

assign mmap_ARLEN = n[31:0];

assign sext_ln17_fu_131_p1 = $signed(trunc_ln17_1_fu_121_p4);

assign stream_V_din = mmap_addr_read_reg_191;

assign trunc_ln17_1_fu_121_p4 = {{mmap_offset[63:2]}};

endmodule //Mmap2Stream
